FROM golang:1.25-alpine

WORKDIR /workspace/services/nature-service
COPY contracts/go /workspace/contracts/go
COPY family-platform/go /workspace/family-platform/go
COPY services/nature-service/go.mod services/nature-service/go.sum ./
RUN go mod download

CMD ["go", "run", "./cmd/service"]
