FROM golang:1.25-alpine

WORKDIR /workspace/services/analytics-service
COPY contracts/go /workspace/contracts/go
COPY services/analytics-service/go.mod services/analytics-service/go.sum ./
RUN go mod download

CMD ["go", "run", "./cmd/service"]
